"""add evidence source external id constraint

Revision ID: 4c6927b4b860
Revises: 636e8bb960df
Create Date: 2026-08-31 22:32:02.034494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4c6927b4b860"
down_revision: Union[str, Sequence[str], None] = "636e8bb960df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incident_evidence",
        sa.Column(
            "source", sa.String(length=50), nullable=False, server_default="manual"
        ),
    )
    op.add_column(
        "incident_evidence",
        sa.Column("external_id", sa.String(length=255), nullable=True),
    )
    op.create_unique_constraint(
        "uq_incident_evidence_external",
        "incident_evidence",
        ["incident_id", "source", "external_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_incident_evidence_external", "incident_evidence", type_="unique"
    )
    op.drop_column("incident_evidence", "external_id")
    op.drop_column("incident_evidence", "source")
    # ### end Alembic commands ###
