"""add integration webhook secret

Revision ID: 5ac5841e1a0d
Revises: 5aefeab5c9ff
Create Date: 2026-09-24 14:08:22.073067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac5841e1a0d'
down_revision: Union[str, Sequence[str], None] = '5aefeab5c9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Integrations', sa.Column('webhook_secret', sa.String(), nullable=True))
    
    from sqlalchemy.dialects import postgresql
    status_enum = postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='automationjobstatus')
    status_enum.create(op.get_bind(), checkfirst=True)
    
    op.execute("ALTER TABLE incident_automation_jobs ALTER COLUMN status TYPE automationjobstatus USING status::automationjobstatus")
    op.create_index('ix_automation_job_tenant_incident', 'incident_automation_jobs', ['tenant_id', 'incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automation_job_tenant_incident', table_name='incident_automation_jobs')
    op.alter_column('incident_automation_jobs', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='automationjobstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('Integrations', 'webhook_secret')
    # ### end Alembic commands ###
