"""added the incident action model

Revision ID: 7a96b5699c7a
Revises: 788626d90288
Create Date: 2026-09-22 16:35:28.468169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a96b5699c7a'
down_revision: Union[str, Sequence[str], None] = '788626d90288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_actions_incident_id'), 'incident_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_actions_performed_by'), 'incident_actions', ['performed_by'], unique=False)
    op.create_index(op.f('ix_incident_actions_phase'), 'incident_actions', ['phase'], unique=False)
    op.create_index(op.f('ix_incident_actions_tenant_id'), 'incident_actions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_actions_tenant_id'), table_name='incident_actions')
    op.drop_index(op.f('ix_incident_actions_phase'), table_name='incident_actions')
    op.drop_index(op.f('ix_incident_actions_performed_by'), table_name='incident_actions')
    op.drop_index(op.f('ix_incident_actions_incident_id'), table_name='incident_actions')
    op.drop_table('incident_actions')
    # ### end Alembic commands ###
